services:
  web-server:
    build:
      dockerfile: Dockerfile 
      context: .
    restart: always
    volumes:
      - "./:/var/www/html"
    ports:
      - "8080:80"
  mysql-server:
    image: mysql:9.1
    restart: always
    env_file:
      - .env
    ports:
      - "3316:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - "./database:/docker-entrypoint-initdb.d"
volumes:
  mysql-data:
    driver: local
