services:
  web-server:
    build:
      dockerfile: Dockerfile 
      context: .
    restart: always
    volumes:
      - "./:/var/www/html"
    ports:
      - "8080:80"
    env_file:
      - .env
  mysql-server:
    image: mysql:9.1
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - "mysql-volume:/var/lib/mysql"
      - "./database:/docker-entrypoint-initdb.d"
volumes:
  mysql-volume:
    driver: local
