name: ci

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup NPM
        uses: actions/setup-node@v4.2.0
      - name: Install dependencies
        run: npm install
      - name: Compile Typescript
        run: npm run compile-ts
      - name: Compile SCSS
        run: npm run compile-scss
      - name: Create ZIP file
        run: zip -r Site-pre-conceito-AHSD.zip LICENSE README.md *.html *.php visoes/ Dockerfile docker-compose.yaml javascript/ css/ database/ img/
      - name: Save ZIP file
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./Site-pre-conceito-AHSD.zip
          name: Site-pre-conceito-AHSD.zip

  create-release:
    permissions:
      contents: write

    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Retrieve ZIP file
        uses: actions/download-artifact@v4.1.9
        with:
          name: Site-pre-conceito-AHSD.zip
      - name: Calculate SHA256SUM
        run: sha256sum Site-pre-conceito-AHSD.zip > Site-pre-conceito-AHSD.zip.sha256sum
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Site-pre-conceito-AHSD.zip
            Site-pre-conceito-AHSD.zip.sha256sum
          make_latest: true
